### PR TITLE
Submitting the cesium-navigation plugin to the cesium-plugins-list. Please review.

### PR DESCRIPTION
**Pull request by alberto-acevedo**
Please review.my plugin and let me know if there is something else I have to do to complete the review.

Thanks,

Alberto

### CODE REVIEW

**Comment by alberto-acevedo** [comment]
Added the cesium-navigation plugin to the index.html.
Added a png image.

**Comment by pjcozzi** [comment]
Thanks @alberto-acevedo!

@ggetz can you merge this and update the website submodule?

**Comment by pjcozzi** [comment]
Thanks @ggetz.  Can you please crop the image so the aspect ratio is consistent?

http://cesiumjs.org/plugins/

**Comment by pjcozzi** [comment]
Can we also please include @alberto-acevedo's name instead of just saying "Contact" in the right column.

**Comment by ggetz** [comment]
I cropped the image and updated @alberto-acevedo's name in a2dfb2cb17ba7f860b67dc41593c4411c6beee69

**Pull request merged**
