### PR TITLE
cesium-elevation-gradient

### PR DESCRIPTION
**Pull request by chris-cooper**
As presented at the 2016 SIGGRAPH Cesium BOF.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks @chris-cooper.  We'll try to merge and deploy this tomorrow along with a SIGGRAPH trip report that I am writing that mentions this.

Very cool stuff, thanks for making it open-source!

**Comment by chris-cooper** [comment]
You're welcome, hopefully it will encourage others to do similar.  Longer term it might be worth thinking on some updated guidelines for Cesium plugins so they're simple to author, publish and build into Cesium apps via npm.

**Comment by pjcozzi** [comment]
Sorry for the delay; the fall has been busy to say the least.

@ggetz could you please publish this?

**Comment by pjcozzi** [comment]
@ggetz can you also update the website submodule so this will be deployed?

**Pull request merged**
